# Default configuration for rubocop-rspec_parity

RSpecParity/FileHasSpec:
  Description: 'Checks that each Ruby file in the app directory has a corresponding spec file.'
  Enabled: true
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/assets/**/*'
    - 'app/views/**/*'
    - 'app/javascript/**/*'

RSpecParity/PublicMethodHasSpec:
  Description: 'Checks that each public method has a corresponding spec test.'
  Enabled: true
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/assets/**/*'
    - 'app/views/**/*'
    - 'app/javascript/**/*'

RSpecParity/SufficientContexts:
  Description: 'Ensures specs have at least as many contexts as the method has branches.'
  Enabled: true
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/assets/**/*'
    - 'app/views/**/*'
    - 'app/javascript/**/*'

RSpecParity/NoLetBang:
  Description: 'Disallows the use of `let!` in specs.'
  Enabled: true
  Include:
    - 'spec/**/*_spec.rb'
