# Default configuration for rubocop-spec_parity

SpecParity/FileHasSpec:
  Description: 'Checks that each Ruby file in the app directory has a corresponding spec file.'
  Enabled: true
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/assets/**/*'
    - 'app/views/**/*'
    - 'app/javascript/**/*'

SpecParity/PublicMethodHasSpec:
  Description: 'Checks that each public method has a corresponding spec test.'
  Enabled: true
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/assets/**/*'
    - 'app/views/**/*'
    - 'app/javascript/**/*'

SpecParity/NoLetBang:
  Description: 'Disallows the use of `let!` in specs.'
  Enabled: true
  Include:
    - 'spec/**/*_spec.rb'
